package by.neuhen.task01javabasic.controller;

public enum CommandType {
    FUNC_Z,
    FUNC_C,
    RESISTANCE,
    MULT_DIGITS_OF_NUMBER,
    CUBE_ARITHMETIC,

    DOT_LOCATION,
    DOUBLE_NUMBERS,
    EXERCISE_ONE,
    EXERCISE_TWO,
    NEGATIVE_NUMBER_COUNT,

    ADD_AND_MULTIPLY,
    NUMBER_SERIES,
    DESCENDING_STRING,
    EVEN_STRING,
    ROME_DIGITS_TO_ARABIC,

    EXIT
}
